name: Beta macOS

on:
  push:
    branches:
      - beta
  workflow_dispatch:

jobs:
  build:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: client
        run: npm install

      - name: Build
        working-directory: client
        run: npm run build:mac

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Electron-macOS-beta
          path: client/dist/*.dmg
